
import { jsPDF } from 'jspdf';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import type { ExtractedClinicalData } from '../lib/ai';
import { ArrowLeft, Download, Share2, ClipboardCopy, AlertTriangle } from 'lucide-preact';

interface ReferralLetterProps {
  data: ExtractedClinicalData;
  onBack: () => void;
}

export function ReferralLetter({ data, onBack }: ReferralLetterProps) {
  
  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(220, 38, 38); // Red
    doc.text("URGENT MEDICAL REFERRAL", 105, 20, { align: "center" });
    
    // Date & Source
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Source: Saheli CHW Triage System`, 14, 35);
    
    // Line
    doc.setLineWidth(0.5);
    doc.line(14, 40, 196, 40);

    // Patient Info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Patient Information", 14, 50);
    doc.setFontSize(11);
    doc.text(`Initials: ${data.patientInitials || 'Not provided'}`, 14, 58);
    doc.text(`Age: ${data.age || 'N/A'} yrs`, 14, 65);
    doc.text(`Sex: ${data.sex || 'N/A'}`, 80, 65);
    
    // Clinical Findings
    doc.setFontSize(14);
    doc.text("Clinical Findings", 14, 80);
    doc.setFontSize(11);
    doc.text(`Symptoms: ${data.symptoms.join(', ')}`, 14, 88);
    if (data.duration) doc.text(`Duration: ${data.duration}`, 14, 95);

    // Danger Signs (RED)
    if (data.dangerSigns && data.dangerSigns.length > 0) {
      doc.setTextColor(220, 38, 38);
      doc.setFontSize(12);
      doc.text("RED FLAGS / DANGER SIGNS IDENTIFIED:", 14, 110);
      
      doc.setFontSize(11);
      let y = 118;
      data.dangerSigns.forEach((sign) => {
        doc.text(`- ${sign}`, 18, y);
        y += 7;
      });
      doc.setTextColor(0, 0, 0);
    }

    // Action Taken & Draft
    doc.setFontSize(14);
    doc.text("Action Taken locally", 14, 140);
    doc.setFontSize(11);
    let y = 148;
    data.actionSteps.forEach(step => {
      const split = doc.splitTextToSize(`- ${step}`, 180);
      doc.text(split, 14, y);
      y += 7 * split.length;
    });

    if (data.referralLetterDraft) {
      y += 10;
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const split = doc.splitTextToSize(`AI Notes: ${data.referralLetterDraft}`, 180);
      doc.text(split, 14, y);
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("This letter was generated by an automated clinical decision support tool.", 105, 280, { align: "center" });

    doc.save(`Referral_${data.patientInitials || 'Patient'}_${Date.now()}.pdf`);
  };

  const shareViaWhatsApp = () => {
    const text = `*URGENT REFERRAL*\nPatient: ${data.patientInitials || 'Unknown'}\nAge/Sex: ${data.age||'N/A'}/${data.sex||'N/A'}\nSymptoms: ${data.symptoms.join(', ')}\n*Danger Signs*: ${data.dangerSigns.join(', ')}\nAction Taken: ${data.actionSteps.join(', ')}\n\n_Generated via Saheli Triage_`;
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const copyToClipboard = () => {
    const text = `URGENT REFERRAL\nPatient: ${data.patientInitials || 'Unknown'}\nAge/Sex: ${data.age||'N/A'}/${data.sex||'N/A'}\nSymptoms: ${data.symptoms.join(', ')}\nDanger Signs: ${data.dangerSigns.join(', ')}\nAction Taken: ${data.actionSteps.join(', ')}`;
    navigator.clipboard.writeText(text);
    alert('Copied to clipboard!');
  };

  return (
    <div class="flex flex-col h-full animate-in fade-in slide-in-from-right-2 duration-300">
      
      <div class="flex items-center gap-3 mb-6">
        <button onClick={onBack} class="p-2 -ml-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
          <ArrowLeft class="w-6 h-6 text-slate-700 dark:text-slate-300" />
        </button>
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white">Referral Letter</h2>
      </div>

      <Card class="flex-1 overflow-y-auto mb-6 p-5 border-2 border-red-500/20 bg-red-50/50 dark:bg-red-900/10 dark:border-red-900/50 relative">
        <div class="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
          <AlertTriangle class="w-32 h-32 text-red-500" />
        </div>
        
        <h3 class="text-xl font-black text-red-700 dark:text-red-400 mb-4 border-b border-red-200 dark:border-red-900/50 pb-2">
          URGENT REFERRAL
        </h3>
        
        <div class="space-y-4 text-slate-800 dark:text-slate-200 relative z-10 font-medium">
          <div>
            <span class="text-slate-500 dark:text-slate-400 block text-xs font-bold uppercase tracking-wider mb-1">Patient</span>
            <p className="font-bold text-lg">{data.patientInitials || 'Not specified'} • {data.age ? `${data.age} yrs` : '?'} • {data.sex || '?'}</p>
          </div>
          
          <div>
            <span class="text-slate-500 dark:text-slate-400 block text-xs font-bold uppercase tracking-wider mb-1">Signs & Symptoms</span>
            <p>{data.symptoms.join(', ')}</p>
            {data.duration && <p class="text-sm mt-1 text-slate-600 dark:text-slate-400">Duration: {data.duration}</p>}
          </div>

          <div>
            <span class="text-red-600 dark:text-red-400 block text-xs font-black uppercase tracking-wider mb-1">Danger Signs</span>
            <ul class="list-disc pl-5 font-bold text-red-700 dark:text-red-300">
              {data.dangerSigns.map(sign => <li key={sign}>{sign}</li>)}
            </ul>
          </div>

          <div>
            <span class="text-slate-500 dark:text-slate-400 block text-xs font-bold uppercase tracking-wider mb-1">Action Taken</span>
            <ul class="list-disc pl-5">
              {data.actionSteps.map(step => <li key={step}>{step}</li>)}
            </ul>
          </div>
          
          {data.referralLetterDraft && (
            <div class="bg-white/60 dark:bg-black/20 p-3 rounded-lg mt-4 text-sm font-normal italic border border-slate-200 dark:border-slate-800">
              {data.referralLetterDraft}
            </div>
          )}
        </div>
      </Card>

      <div class="grid grid-cols-1 gap-3 pb-2 pt-2 border-t dark:border-slate-800">
        <Button variant="danger" class="w-full gap-2 shadow-sm" onClick={generatePDF}>
          <Download class="w-5 h-5" /> Download PDF
        </Button>
        <div class="grid grid-cols-2 gap-3 mt-1">
          <Button variant="secondary" class="gap-2 text-slate-700 dark:text-slate-300 shadow-sm" onClick={shareViaWhatsApp}>
            <Share2 class="w-4 h-4" /> Share
          </Button>
          <Button variant="secondary" class="gap-2 text-slate-700 dark:text-slate-300 shadow-sm" onClick={copyToClipboard}>
            <ClipboardCopy class="w-4 h-4" /> Copy Text
          </Button>
        </div>
      </div>

    </div>
  );
}
